apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: hello-world-linux
    custom:
      buildCommand: APP=hello-world-linux make build-and-push-debug
manifests:
  rawYaml:
  - cmd/hello-world-linux/deploy/hello-world-linux.yaml
deploy:
  kubectl: {}
