kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
    controllerManager:
      extraArgs:
        v: "5"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    kubelet:
      extraArgs:
        v: "5"
