apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-linux
  namespace: sandbox
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-world-linux-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-world-linux-role-binding
subjects:
  - kind: ServiceAccount
    name: hello-world-linux
    namespace: sandbox
roleRef:
  kind: ClusterRole
  name: hello-world-linux-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-linux
  namespace: sandbox
  annotations:
    # https://kubernetes.io/docs/tutorials/clusters/apparmor/
    container.apparmor.security.beta.kubernetes.io/hello-world-linux: unconfined
spec:
  serviceAccount: hello-world-linux
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: hello-world-linux
    image: hello-world-linux
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
