apiVersion: skaffold/v2beta15
kind: Config
build:
  artifacts:
  - image: hello-world-windows
    custom:
      buildCommand: APP=hello-world-windows make build-and-push-multi-arch-debug
deploy:
  kubectl:
    manifests:
      - cmd/hello-world-windows/deploy/hello-world-windows.yaml
