apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: hello-world-windows
    custom:
      buildCommand: APP=hello-world-windows make build-and-push-multi-arch-debug
manifests:
  rawYaml:
  - cmd/hello-world-windows/deploy/hello-world-windows.yaml
deploy:
  kubectl: {}
